[book]
authors = ["FledgeXu"]
language = "en"
multilingual = false
src = "src"
title = "Minecraft Forge Mod Dev tutorial"
[output.html]
mathjax-support = true
google-analytics = "UA-80068655-2"
[output.linkcheck]
